name: Deploy snapshot to Maven S3

# Run workflow when the workflow to check the quality is completed
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  publish-package:
    permissions:
      contents: read
      packages: write
    uses: maxxq-org/maxxq-workflows/.github/workflows/maven-publish-snapshot-s3.yml@main
    with:
      java-version: '17'
      java-distribution: 'temurin'
    secrets: inherit
